### ISSUE TITLE
Cannot render pure component with jsx

### ISSUE THREAD

**Issue by Kornflexx** [jorgebucaran/superfine#123]
Hello,

First of all, thank you for your work.
I encounter an issue trying to run the last example (others examples works with jsx).

```
import { h, render } from "superfine"

const ClickMe = props => (
  <a href={props.url}>
    <h1>{children}</h1>
  </a>
)

let lastNode = render(
  null,
  <ClickMe url="/">Click Here!</ClickMe>,
  document.body
)
```

In my browser console I have the following error:

```
VM9945:1 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('function ClickMe(props) {
  return (0, _superfine.h)("a", {
    href: props.url
  }, (0, _superfine.h)("h1", null, children));
}') is not a valid name.
    at HTMLDocument.createElement (<anonymous>:1:1554)
    at createElement (webpack:///./node_modules/superfine/src/index.js?:51:20)
    at patchElement (webpack:///./node_modules/superfine/src/index.js?:132:7)
    at render (webpack:///./node_modules/superfine/src/index.js?:258:3)
    at eval (webpack:///./src/index.js?:11:38)
    at Object../src/index.js (http://localhost:3000/index.js:384:1)
    at __webpack_require__ (http://localhost:3000/index.js:20:30)
    at eval (webpack:///multi_(webpack)-dev-server/client?:2:18)
    at Object.0 (http://localhost:3000/index.js:395:1)
    at __webpack_require__ (http://localhost:3000/index.js:20:30)
(anonymous) @ VM9945:1
createElement @ index.js:51
patchElement @ index.js:132
render @ index.js:258
(anonymous) @ index.js:11
./src/index.js @ index.js:384
__webpack_require__ @ index.js:20
(anonymous) @ client:2
0 @ index.js:395
__webpack_require__ @ index.js:20
(anonymous) @ index.js:84
(anonymous) @ index.js:87
```

Here are my configs:

`.babelrc`
```
{
    "presets": [
        "@babel/preset-env"
    ],
    "plugins": [
        [
            "transform-react-jsx",
            {
                "pragma": "h"
            }
        ]
    ]
}
```

`webpack.config.js`
```
const path = require('path')

module.exports = {
    entry: './src/index.js',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'index.js'
    },
    mode: 'development',
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        babelrc: true
                    }
                }
            }
        ]
    },
    devServer: {
        contentBase: path.resolve(__dirname, 'dist'),
        compress: true,
        port: 3000
    }
};
```

`package.json`
```
{
  "name": "superfine-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --watch",
    "build": "webpack",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "superfine": "^5.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.51",
    "@babel/preset-env": "^7.0.0-beta.51",
    "babel-cli": "^6.26.0",
    "babel-loader": "^8.0.0-beta.4",
    "babel-plugin-auto-import": "^0.7.1",
    "babel-preset-env": "^1.7.0",
    "webpack": "^4.12.2",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2"
  }
}
```

**Comment by jorgebucaran** [comment]
https://github.com/jorgebucaran/superfine/issues/120

**Comment by jorgebucaran** [comment]
Thanks, @Kornflexx. It's added here 0b9667a38fff30f9f68694bdbaea8ac2af477d62, I just need to cut  a new release. 👋
